openapi: 3.1.0
info:
  title: Car Maintenance Tracker API
  version: 1.0.0
servers:
- url: /
paths:
  /users:
    post:
      description: Registers a new user using email and password
      operationId: create
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRegistrationRequest'
        required: true
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/create_201_response'
          description: User successfully created
      summary: Create a new user
      tags:
      - users
      x-content-type: application/json
      x-accepts:
      - application/json
components:
  schemas:
    UserResponse:
      properties:
        id:
          example: 1
          format: int64
          type: integer
        email:
          example: user@example.com
          format: email
          type: string
    UserRegistrationRequest:
      example:
        password: StrongPass123!
        passwordRepeat: StrongPass123!
        email: user@example.com
      properties:
        email:
          example: user@example.com
          format: email
          type: string
        password:
          example: StrongPass123!
          format: password
          minLength: 8
          type: string
        passwordRepeat:
          example: StrongPass123!
          format: password
          minLength: 8
          type: string
      required:
      - email
      - password
      - passwordRepeat
    create_201_response:
      $ref: '#/components/schemas/UserResponse'

