openapi: 3.1.0
info:
  title: Car Maintenance Tracker API
  version: 1.0.0


paths:
  /users:
    post:
      summary: Create a new user
      description: Registers a new user using email and password
      operationId: create
      tags:
        - users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRegistrationRequest'

      responses:
        '201':
          description: User successfully created
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    example: "abc123"
                $ref: '#/components/schemas/UserResponse'


components:
  schemas:

    UserResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        email:
          type: string
          format: email
          example: user@example.com



    UserRegistrationRequest:
      type: object
      required:
        - email
        - password
        - passwordRepeat
      properties:
        email:
          type: string
          format: email
          example: user@example.com
        password:
          type: string
          format: password
          minLength: 8
          example: StrongPass123!
        passwordRepeat:
          type: string
          format: password
          minLength: 8
          example: StrongPass123!
